### ISSUE TITLE
The player won't start

### ISSUE THREAD

**Issue by mad-max-traveller** [nukeop/nuclear#1119]
**Platform:**
KDE neon 5.23
5.11.0-41-generic

**Nuclear version:**
$ sudo snap info nuclear
name:      nuclear
summary:   nuclear
publisher: nukeop
store-url: https://snapcraft.io/nuclear
contact:   https://github.com/nukeop/nuclear/issues
license:   unset
description: |
  Streaming music player that finds music sources automatically.
commands:
  - nuclear
snap-id:      yivm0p7LFQ6ocuH1kZCLnb70aVMJNZnA
tracking:     latest/stable
refresh-date: today at 10:42 +07
channels:
  latest/stable:    0.6.17 2021-11-01 (18) 95MB -
  latest/candidate: ↑                           
  latest/beta:      ↑                           
  latest/edge:      ↑                           
installed:          0.6.17            (18) 95MB -

**Description of the issue:**
Hi. Installed the player with snap.
The player won't start.

**Comment by interrupter** [comment]
Same issue. Console output below.

`      main › (node:1982767) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)

(nuclear:1982767): dbind-WARNING **: 10:37:53.494: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-kJ8xXiUmCq: No such file or directory
      main › Sqlite database creation failed
      main › t: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
    at t [as constructor] (/snap/nuclear/18/resources/app.asar/dist/main.js:2720:778599)
    at new t (/snap/nuclear/18/resources/app.asar/dist/main.js:2720:754777)
    at t.loadDependencies (/snap/nuclear/18/resources/app.asar/dist/main.js:2720:618480)
    at new t (/snap/nuclear/18/resources/app.asar/dist/main.js:2720:617021)
    at e.create (/snap/nuclear/18/resources/app.asar/dist/main.js:2720:70933)
    at new e (/snap/nuclear/18/resources/app.asar/dist/main.js:2720:24027)
    at e.create (/snap/nuclear/18/resources/app.asar/dist/main.js:2720:32826)
    at /snap/nuclear/18/resources/app.asar/dist/main.js:2720:801588
    at /snap/nuclear/18/resources/app.asar/dist/main.js:2739:2716
    at Object.next (/snap/nuclear/18/resources/app.asar/dist/main.js:2739:2821)
    at /snap/nuclear/18/resources/app.asar/dist/main.js:2739:1758
    at new Promise (<anonymous>)
    at Module.c (/snap/nuclear/18/resources/app.asar/dist/main.js:2739:1503)
    at t.createConnection (/snap/nuclear/18/resources/app.asar/dist/main.js:2720:801322)
    at Tn.connect (/snap/nuclear/18/resources/app.asar/dist/main.js:2751:496229)
    at App.<anonymous> (/snap/nuclear/18/resources/app.asar/dist/main.js:2751:537307)
    at App.emit (events.js:327:22)
      main › (node:1982767) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([
  'Connection ":1.1010" is not allowed to own the service "org.mpris.MediaPlayer2.org.js.nuclear.Nuclear" due to AppArmor policy'
])
    at gr.emit (events.js:304:17)
    at n (/snap/nuclear/18/resources/app.asar/dist/main.js:2590:16332)
    at /snap/nuclear/18/resources/app.asar/dist/main.js:2590:16589
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
      main › (node:1982767) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
      main › (node:1982767) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by nukeop** [comment]
This has been fixed in the newest release.
