### ISSUE TITLE
Error: Cannot find module '/package.json'

### ISSUE THREAD

**Issue by zeromold** [nukeop/nuclear#1176]
**Platform:**
Linux pop-os 5.15.11-76051511-generic #202112220937~1640185481~21.04~b3a2c21-Ubuntu SMP Mon Jan 3 16:5 x86_64 x86_64 x86_64 GNU/Linux

**Nuclear version:**
nuclear v0.6.17 
installed from  nuclear-v0.6.17.deb

**Description of the issue:**

nuclear opens but is unable to play anything.

nuclear
      main › (node:8306) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
      main › (node:8306) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'write' of null
    at e.exports.send (/opt/nuclear/resources/app.asar/dist/main.js:2200:13798)
    at /opt/nuclear/resources/app.asar/dist/main.js:2200:2154
    at new Promise (<anonymous>)
    at e.exports.request (/opt/nuclear/resources/app.asar/dist/main.js:2200:2107)
    at e.exports.clearActivity (/opt/nuclear/resources/app.asar/dist/main.js:2200:6785)
    at fr.clear (/opt/nuclear/resources/app.asar/dist/main.js:2751:510734)
    at ca.onClearTrackList (/opt/nuclear/resources/app.asar/dist/main.js:2751:531161)
    at IpcMainImpl.<anonymous> (/opt/nuclear/resources/app.asar/dist/main.js:2751:536446)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
      main › (node:8306) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
      main › (node:8306) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
-----

    main › (node:8306) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
      main › (node:8306) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'write' of null
    at e.exports.send (/opt/nuclear/resources/app.asar/dist/main.js:2200:13798)
    at /opt/nuclear/resources/app.asar/dist/main.js:2200:2154
    at new Promise (<anonymous>)
    at e.exports.request (/opt/nuclear/resources/app.asar/dist/main.js:2200:2107)
    at e.exports.clearActivity (/opt/nuclear/resources/app.asar/dist/main.js:2200:6785)
    at fr.clear (/opt/nuclear/resources/app.asar/dist/main.js:2751:510734)
    at ca.onClearTrackList (/opt/nuclear/resources/app.asar/dist/main.js:2751:531161)
    at IpcMainImpl.<anonymous> (/opt/nuclear/resources/app.asar/dist/main.js:2751:536446)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
      main › (node:8306) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
      main › (node:8306) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

nuclear --trace-deprecation 
      main › (node:9092) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
  renderer › Error: Cannot find module '/package.json'
    at n (file:///opt/nuclear/resources/app.asar/dist/renderer.js:1:162754)
    at M (file:///opt/nuclear/resources/app.asar/dist/1.renderer.js:2685:83672)
    at e.exports (file:///opt/nuclear/resources/app.asar/dist/1.renderer.js:2685:84166)
    at file:///opt/nuclear/resources/app.asar/dist/1.renderer.js:2685:80126
    at Array.map (<anonymous>)
    at e.exports (file:///opt/nuclear/resources/app.asar/dist/1.renderer.js:2685:80119)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.t.liveStreamSearch (file:///opt/nuclear/resources/app.asar/dist/1.renderer.js:2685:168100)
    at async file:///opt/nuclear/resources/app.asar/dist/renderer.js:1:215725
    at async Promise.all (index 5)
  renderer › Error: Cannot find module '/package.json'
    at n (file:///opt/nuclear/resources/app.asar/dist/renderer.js:1:162754)
    at M (file:///opt/nuclear/resources/app.asar/dist/1.renderer.js:2685:83672)
    at e.exports (file:///opt/nuclear/resources/app.asar/dist/1.renderer.js:2685:84166)
    at file:///opt/nuclear/resources/app.asar/dist/1.renderer.js:2685:80126
    at Array.map (<anonymous>)
    at e.exports (file:///opt/nuclear/resources/app.asar/dist/1.renderer.js:2685:80119)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.t.liveStreamSearch (file:///opt/nuclear/resources/app.asar/dist/1.renderer.js:2685:168100)
    at async file:///opt/nuclear/resources/app.asar/dist/renderer.js:1:215725
    at async Promise.all (index 5)
      main › (node:9092) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'write' of null
    at e.exports.send (/opt/nuclear/resources/app.asar/dist/main.js:2200:13798)
    at /opt/nuclear/resources/app.asar/dist/main.js:2200:2154
    at new Promise (<anonymous>)
    at e.exports.request (/opt/nuclear/resources/app.asar/dist/main.js:2200:2107)
    at e.exports.clearActivity (/opt/nuclear/resources/app.asar/dist/main.js:2200:6785)
    at fr.clear (/opt/nuclear/resources/app.asar/dist/main.js:2751:510734)
    at ca.onClearTrackList (/opt/nuclear/resources/app.asar/dist/main.js:2751:531161)
    at IpcMainImpl.<anonymous> (/opt/nuclear/resources/app.asar/dist/main.js:2751:536446)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
      main › (node:9092) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
      main › (node:9092) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  renderer › Error while searching  for The O'Jays Back Stabbers on Youtube
  renderer › Error: Cannot find module '/package.json'
    at n (file:///opt/nuclear/resources/app.asar/dist/renderer.js:1:162754)
    at M (file:///opt/nuclear/resources/app.asar/dist/1.renderer.js:2685:83672)
    at e.exports (file:///opt/nuclear/resources/app.asar/dist/1.renderer.js:2685:84166)
    at file:///opt/nuclear/resources/app.asar/dist/1.renderer.js:2685:80126
    at Array.map (<anonymous>)
    at e.exports (file:///opt/nuclear/resources/app.asar/dist/1.renderer.js:2685:80119)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async N (file:///opt/nuclear/resources/app.asar/dist/1.renderer.js:2685:166608)
    at async c.search (file:///opt/nuclear/resources/app.asar/dist/1.renderer.js:2685:147218)
    at async file:///opt/nuclear/resources/app.asar/dist/renderer.js:1:207770
    at async file:///opt/nuclear/resources/app.asar/dist/renderer.js:1:207486
      main › (node:9092) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'write' of null
    at e.exports.send (/opt/nuclear/resources/app.asar/dist/main.js:2200:13798)
    at /opt/nuclear/resources/app.asar/dist/main.js:2200:2154
    at new Promise (<anonymous>)
    at e.exports.request (/opt/nuclear/resources/app.asar/dist/main.js:2200:2107)
    at e.exports.clearActivity (/opt/nuclear/resources/app.asar/dist/main.js:2200:6785)
    at fr.clear (/opt/nuclear/resources/app.asar/dist/main.js:2751:510734)
    at App.<anonymous> (/opt/nuclear/resources/app.asar/dist/main.js:2751:537783)
    at App.emit (events.js:327:22)
    at Lt.close (/opt/nuclear/resources/app.asar/dist/main.js:2751:486639)
    at ha.onClose (/opt/nuclear/resources/app.asar/dist/main.js:2751:533655)
    at IpcMainImpl.<anonymous> (/opt/nuclear/resources/app.asar/dist/main.js:2751:536446)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
      main › (node:9092) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

-----

     main › (node:9385) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
  renderer › Error: Cannot find module '/package.json'
    at n (file:///opt/nuclear/resources/app.asar/dist/renderer.js:1:162754)
    at M (file:///opt/nuclear/resources/app.asar/dist/1.renderer.js:2685:83672)
    at e.exports (file:///opt/nuclear/resources/app.asar/dist/1.renderer.js:2685:84166)
    at file:///opt/nuclear/resources/app.asar/dist/1.renderer.js:2685:80126
    at Array.map (<anonymous>)
    at e.exports (file:///opt/nuclear/resources/app.asar/dist/1.renderer.js:2685:80119)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.t.liveStreamSearch (file:///opt/nuclear/resources/app.asar/dist/1.renderer.js:2685:168100)
    at async file:///opt/nuclear/resources/app.asar/dist/renderer.js:1:215725
    at async Promise.all (index 5)
      main › error trying to set discord activity
      main › (node:9385) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'write' of null
    at e.exports.send (/opt/nuclear/resources/app.asar/dist/main.js:2200:13798)
    at /opt/nuclear/resources/app.asar/dist/main.js:2200:2154
    at new Promise (<anonymous>)
    at e.exports.request (/opt/nuclear/resources/app.asar/dist/main.js:2200:2107)
    at e.exports.clearActivity (/opt/nuclear/resources/app.asar/dist/main.js:2200:6785)
    at fr.clear (/opt/nuclear/resources/app.asar/dist/main.js:2751:510734)
    at App.<anonymous> (/opt/nuclear/resources/app.asar/dist/main.js:2751:537783)
    at App.emit (events.js:327:22)
    at Lt.close (/opt/nuclear/resources/app.asar/dist/main.js:2751:486639)
    at ha.onClose (/opt/nuclear/resources/app.asar/dist/main.js:2751:533655)
    at IpcMainImpl.<anonymous> (/opt/nuclear/resources/app.asar/dist/main.js:2751:536446)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
      main › (node:9385) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
      main › (node:9385) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
   ipc api › error in event start-download => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at Lt.send (/opt/nuclear/resources/app.asar/dist/main.js:2751:485660)
    at Qt.onStartDownload (/opt/nuclear/resources/app.asar/dist/main.js:2751:489414)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by nukeop** [comment]
Can anyone reproduce this on Pop OS?

**Comment by WolfangAukang** [comment]
Not on Pop_OS, but on NixOS, I have the same issue. Installed the Appimage.

**Comment by nukeop** [comment]
It's hard to say what's happening here, but
1. `clearActivity` is a discord-related method
2. It contains a promise and it's not awaited
3. It's not called in a try-catch block
So it might be this. Even if you're not using discord though, this should not be throwing errors. I'll add some defensive code around it.

**Comment by nukeop** [comment]
I fixed this uncaught potential error and added a test for it.

**Comment by WolfangAukang** [comment]
FYI, the error is indeed caught:
```
main › error trying to set discord activity
```

But when I closed the application, I got the same uncaught error:
```
main › Something failed during app close
      main › TypeError: Cannot read property 'write' of null
    at e.exports.send (/nix/store/waxm22s0f9c4fnx5smnjayqk8far22nd-nuclear-nightly-extracted/resources/app.asar/dist/webpack:/home/runner/work/nuclear/nuclear/node_modules/discord-rpc/src/transports/ipc.js:155:17)
    at /nix/store/waxm22s0f9c4fnx5smnjayqk8far22nd-nuclear-nightly-extracted/resources/app.asar/dist/webpack:/home/runner/work/nuclear/nuclear/node_modules/discord-rpc/src/client.js:166:22
    at new Promise (<anonymous>)
    at e.exports.request (/nix/store/waxm22s0f9c4fnx5smnjayqk8far22nd-nuclear-nightly-extracted/resources/app.asar/dist/webpack:/home/runner/work/nuclear/nuclear/node_modules/discord-rpc/src/client.js:164:12)
    at e.exports.clearActivity (/nix/store/waxm22s0f9c4fnx5smnjayqk8far22nd-nuclear-nightly-extracted/resources/app.asar/dist/webpack:/home/runner/work/nuclear/nuclear/node_modules/discord-rpc/src/client.js:550:17)
    at hn.clear (/nix/store/waxm22s0f9c4fnx5smnjayqk8far22nd-nuclear-nightly-extracted/resources/app.asar/dist/webpack:/src/services/discord/index.ts:97:22)
    at App.<anonymous> (/nix/store/waxm22s0f9c4fnx5smnjayqk8far22nd-nuclear-nightly-extracted/resources/app.asar/dist/webpack:/src/main.ts:99:19)
    at App.close [as emit] (events.js:327:22)
    at Lt.close (/nix/store/waxm22s0f9c4fnx5smnjayqk8far22nd-nuclear-nightly-extracted/resources/app.asar/dist/webpack:/src/services/window/index.ts:154:24)
    at fa.name [as onClose] (/nix/store/waxm22s0f9c4fnx5smnjayqk8far22nd-nuclear-nightly-extracted/resources/app.asar/dist/webpack:/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/nix/store/waxm22s0f9c4fnx5smnjayqk8far22nd-nuclear-nightly-extracted/resources/app.asar/dist/webpack:/src/utils/container.ts:54:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
```
