### ISSUE TITLE
JavaScript error when trying to play a track.

### ISSUE THREAD

**Issue by Msouza91** [nukeop/nuclear#1184]
**Platform:**
Fedora 35 (RPM Installer)

**Nuclear version:**
0.6.17

**Description of the issue:**
When trying to play a track that I searched for or put in queue by the autoradio function I get a JavaScript error message with an uncaught exception.
![image](https://user-images.githubusercontent.com/19522556/152156250-e3d7c024-7a02-4567-8fcc-94ccc1045737.png)

Transcript of the error message (Done with OCR, may have incorrect characters)
```
Uncaught Exception: Error: Tried to write a message to a closed stream
at EventEmitter.l.on.t.message (/opt/nuclear/resources/app.asar/dist/main.js:
2174:340200)
at e.exports,sendSignal (/opt/nuclear/resources/app.asar/dist/main.js:
2174:334023)
at EventEmitter.n (/opt/nuclear/resources/app.asar/dist/main.js:2174:365890) at EventEmitter.emit (events.js5:20)
at Function.emitProperties Changed (/opt/nuclear/resources/app.asar/dist/
main.js:2174:362505)
at F.setProperty (/opt/nuclear/resources/app.asar/dist/main.js:2590:20756)
at F.value (/opt/nuclear/resources/app.asar/dist/main.js:2590:59579) at F.value (/opt/nuclear/resources/app.asar/dist/main.js:2590:60525) at F.t.descriptor.value (/opt/nuclear/resources/app.asar/dist/main.js:
2174:361927) at gr.set [as tracks] (/opt/nuclear/resources/app.asar/dist/main.js:2590:17464)
at gr.addTrack (/opt/nuclear/resources/app.asar/dist/main.js:2751:513713) at ca.onAddTrack (/opt/nuclear/resources/app.asar/dist/main.js:2751:530970) at IpcMainimpl<anonymous> (/opt/nuclear/resources/app.asar/dist/main.js:
2751:536446)
at IpcMainimplemit (events.js:315:20) at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
at Object.emit (events.js:315:20)
```

**Comment by nukeop** [comment]
Duplicate and already fixed

**Comment by Msouza91** [comment]
> Duplicate and already fixed

I searched the issues and since it was the latest not nightly realease I assumed incorrectly, my bad. It is fixed in nightly, then?

**Comment by nukeop** [comment]
Yeah, this keeps being reported many times a day.
