### ISSUE TITLE
Fedora cant add local library on mountr

### ISSUE THREAD

**Issue by dann1kid** [nukeop/nuclear#1276]
Fedora cant add local library from mounted devices
![image](https://user-images.githubusercontent.com/40342734/167304314-d2f0101a-9c77-444d-bd4c-8e66528bc656.png)

**Comment by nukeop** [comment]
Can you try running it from the terminal to see if there's anything in the logs?

**Comment by dann1kid** [comment]
If command is nuclear it shows it >
```
[admin@DESKTOP-H2AENON ~]$ nuclear
      main › (node:3994832) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
   ipc api › Service failed to initialize
   ipc api › TypeError: Cannot read property 'indexOf' of undefined
    at Function.getFileName (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/bindings/bindings.js:178:16)
    at t (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/bindings/bindings.js:82:48)
    at Object.call (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/abstract-socket/lib/abstract_socket.js:4:17)
    at __webpack_require__ (/opt/nuclear/resources/app.asar/dist/webpack:/@nuclear/main/webpack/bootstrap:19:32)
    at createStream (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/dbus-next/lib/connection.js:39:23)
    at createConnection (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/dbus-next/lib/connection.js:73:31)
    at createClient (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/dbus-next/index.js:9:20)
    at Object.sessionBus (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/dbus-next/index.js:40:10)
    at n.init (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/mpris-service/dist/index.js:192:20)
    at new super (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/mpris-service/dist/index.js:184:8)
    at new n (/opt/nuclear/resources/app.asar/dist/webpack:/@nuclear/main/src/services/@linux/system-api.ts:50:5)
    at Object.resolveInstance (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/inversify/lib/resolution/instantiation.js:27:12)
    at map (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/inversify/lib/resolution/resolver.js:75:42)
    at Array.map (<anonymous>)
    at Object.resolveInstance (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/inversify/lib/resolution/instantiation.js:46:67)
    at _f (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/inversify/lib/resolution/resolver.js:75:42)
    at Object.resolve (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/inversify/lib/resolution/resolver.js:99:12)
    at this (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/inversify/lib/container/container.js:335:37)
    at c._get (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/inversify/lib/container/container.js:326:22)
    at c.get (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/inversify/lib/container/container.js:243:21)
    at /opt/nuclear/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:47:33
    at Array.forEach (<anonymous>)
   ipc api › Service failed to initialize
   ipc api › TypeError: r(...).connect is not a function
    at createStream (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/dbus-next/lib/connection.js:40:24)
    at createConnection (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/dbus-next/lib/connection.js:73:31)
    at createClient (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/dbus-next/index.js:9:20)
    at Object.sessionBus (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/dbus-next/index.js:40:10)
    at n.init (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/mpris-service/dist/index.js:192:20)
    at new super (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/mpris-service/dist/index.js:184:8)
    at new n (/opt/nuclear/resources/app.asar/dist/webpack:/@nuclear/main/src/services/@linux/system-api.ts:50:5)
    at Object.resolveInstance (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/inversify/lib/resolution/instantiation.js:27:12)
    at map (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/inversify/lib/resolution/resolver.js:75:42)
    at Array.map (<anonymous>)
    at Object.resolveInstance (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/inversify/lib/resolution/instantiation.js:46:67)
    at _f (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/inversify/lib/resolution/resolver.js:75:42)
    at Object.resolve (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/inversify/lib/resolution/resolver.js:99:12)
    at this (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/inversify/lib/container/container.js:335:37)
    at c._get (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/inversify/lib/container/container.js:326:22)
    at c.get (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/inversify/lib/container/container.js:243:21)
    at forEach (/opt/nuclear/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:47:33)
    at Array.forEach (<anonymous>)
    at c.listen (/opt/nuclear/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:41:22)
    at App.<anonymous> (/opt/nuclear/resources/app.asar/dist/webpack:/@nuclear/main/src/main.ts:68:15)
[3994832:0513/192429.558148:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Ловушка трассировки/останова (стек памяти сброшен на диск)

```
