### ISSUE TITLE
Loading time is huge: 11 seconds

### ISSUE THREAD

**Issue by BarbzYHOOL** [nukeop/nuclear#1349]
It takes 11 seconds to load the application. By comparison, Gimp which is pretty slow takes 2 seconds on my computer

Maybe we could have an option to disable the dashboard because I will never listen to the horrible things that are popular and I guess fetching that is increasing the loading time. Other options in that vein could be added as well.

**Comment by nukeop** [comment]
How are you measuring the loading time? The dashboard cannot influence the startup time because it only starts loading after the program has finished its startup.

Similar discussions are in #954

**Comment by BarbzYHOOL** [comment]
I am measuring it with a gnome extension app but also tried with `time flatpak run ...` same result

Here is what happens in the console (errors and warnings probably slow it down):
```sh
main › (node:3) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
Gtk-Message: 19:21:33.929: Failed to load module "xapp-gtk3-module"
Gtk-Message: 19:21:33.929: Failed to load module "appmenu-gtk-module"
Gtk-Message: 19:21:34.009: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:21:34.009: Failed to load module "canberra-gtk-module"
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: image driver extension not found
libGL error: failed to load driver: radeon
libGL error: failed to open /dev/dri/card0: Aucun fichier ou dossier de ce type
libGL error: failed to load driver: radeonsi
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
      main › (node:3) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([ 'org.freedesktop.DBus.Error.ServiceUnknown' ])
    at n.emit (events.js:304:17)
    at emitError (/app/main/resources/app.asar/dist/webpack:/node_modules/mpris-service/dist/index.js:222:10)
    at /app/main/resources/app.asar/dist/webpack:/node_modules/mpris-service/dist/index.js:233:7
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
      main › (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
      main › (node:3) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:80) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `exe --trace-deprecation ...` to show where the warning was created)
^C
```

**Comment by BarbzYHOOL** [comment]
if you fix it, plz hit me up

**Comment by nukeop** [comment]
This issue is from an older version of Nuclear that has been replaced with a complete rewrite. None of the old issues apply to the new codebase.

The old code is preserved on the [legacy/electron](https://github.com/nukeop/nuclear/tree/legacy/electron) branch. If you have feedback about the new version, head to [Discussions](https://github.com/nukeop/nuclear/discussions).
