### ISSUE TITLE
[Flatpak] GPU process isn't usable. Goodbye.

### ISSUE THREAD

**Issue by Duckrinium** [nukeop/nuclear#1455]
**Platform:** EndeavourOS (Arch Linux based distro)

**Nuclear version:** Nuclear v0.6.20 from Flathub

**Description of the issue:**
Basically #1297 2: Electric Boogaloo 
And to confirm, no, `no-sandbox` does not work on Flatpak to me.

```❰duckrinium❙~❱✔≻ flatpak run org.js.nuclear.Nuclear --no-sandbox```
```
      main › (node:3) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
Gtk-Message: 13:41:22.238: Failed to load module "xapp-gtk3-module"
Gtk-Message: 13:41:22.238: Failed to load module "canberra-gtk-module"
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
      main › (node:3) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([ 'org.freedesktop.DBus.Error.ServiceUnknown' ])
    at n.emit (events.js:304:17)
    at emitError (/app/main/resources/app.asar/dist/webpack:/node_modules/mpris-service/dist/index.js:222:10)
    at /app/main/resources/app.asar/dist/webpack:/node_modules/mpris-service/dist/index.js:233:7
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
      main › (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
      main › (node:3) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[3:0421/134124.434307:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
/app/bin/run.sh: line 2:     3 Trace/breakpoint trap   (core dumped) zypak-wrapper /app/main/nuclear
```

Have also tried out some other flags, like `--disable-gpu-compositing` or something like that, still same result.

**Comment by nukeop** [comment]
Thanks for reporting this, are you able to give us any details about your GPU and drivers you're using?

**Comment by Duckrinium** [comment]
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.41.03              Driver Version: 530.41.03    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1660         Off| 00000000:01:00.0  On |                  N/A |
| 31%   46C    P0               28W / 130W|    901MiB /  6144MiB |      8%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

**Comment by Duckrinium** [comment]
if it also would make any difference, it's KDE Plasma, X11 session

**Comment by Duckrinium** [comment]
GitHub have worst issue search engine imaginable, there is another person with similar issue and same distro as I am, having no result with `--no-sandbox as well`, #1384

**Comment by uqlel** [comment]
It also happens to me, but I'm using the AUR package.

**Comment by dillfrescott** [comment]
getting these huge errors after running with `--no-sandbox`:

```
issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
  renderer › An error has occurred when searching for streams with Youtube for "Tyler Hubbard - Dancin’ In The Country."
  renderer › TypeError: A is not iterable
    at Object.t.parseFilters (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:11549832)
    at AsyncFunction.s.getFilters (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:11538279)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async I (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:6682209)
    at async file:///opt/nuclear/resources/app.asar/dist/main.0ad184b7f36803809b3b.js:1:403044
  renderer › An error has occurred when searching for streams with Youtube for "Tyler Hubbard - Dancin’ In The Country."
  renderer › TypeError: A is not iterable
    at Object.t.parseFilters (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:11549832)
    at e.exports (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:11536472)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async I (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:6682267)
    at async file:///opt/nuclear/resources/app.asar/dist/main.0ad184b7f36803809b3b.js:1:403044
  renderer › An error has occurred when searching for streams with Youtube for "Old Dominion - Memory Lane."
  renderer › TypeError: A is not iterable
    at Object.t.parseFilters (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:11549832)
    at e.exports (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:11536472)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async I (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:6682267)
    at async file:///opt/nuclear/resources/app.asar/dist/main.0ad184b7f36803809b3b.js:1:403044
  renderer › An error has occurred when searching for streams with Youtube for "Old Dominion - Memory Lane."
  renderer › TypeError: A is not iterable
    at Object.t.parseFilters (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:11549832)
    at e.exports (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:11536472)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async I (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:6682267)
    at async file:///opt/nuclear/resources/app.asar/dist/main.0ad184b7f36803809b3b.js:1:403044
  renderer › An error has occurred when searching for streams with Youtube for "Old Dominion - Memory Lane."
  renderer › TypeError: A is not iterable
    at Object.t.parseFilters (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:11549832)
    at AsyncFunction.s.getFilters (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:11538279)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async I (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:6682209)
    at async file:///opt/nuclear/resources/app.asar/dist/main.0ad184b7f36803809b3b.js:1:403044
  renderer › An error has occurred when searching for streams with Youtube for "Old Dominion - Memory Lane."
  renderer › TypeError: A is not iterable
    at Object.t.parseFilters (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:11549832)
    at e.exports (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:11536472)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async I (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:6682267)
    at async file:///opt/nuclear/resources/app.asar/dist/main.0ad184b7f36803809b3b.js:1:403044
  renderer › An error has occurred when searching for streams with Youtube for "Old Dominion - Memory Lane."
  renderer › TypeError: A is not iterable
    at Object.t.parseFilters (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:11549832)
    at e.exports (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:11536472)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async I (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:6682267)
    at async file:///opt/nuclear/resources/app.asar/dist/main.0ad184b7f36803809b3b.js:1:403044
  renderer › An error has occurred when searching for streams with Youtube for "Old Dominion - Memory Lane."
  renderer › TypeError: A is not iterable
    at Object.t.parseFilters (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:11549832)
    at e.exports (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:11536472)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async I (file:///opt/nuclear/resources/app.asar/dist/809.c42e6cbfe34d77422805.js:4:6682267)
    at async file:///opt/nuclear/resources/app.asar/dist/main.0ad184b7f36803809b3b.js:1:403044
    ```
