### ISSUE TITLE
0.6.37 Flatpak causes "A JavaScript error occurred in the main process"

### ISSUE THREAD

**Issue by yang-musa** [nukeop/nuclear#1676]
**Platform:**
Fedora 40, fully up to date

**Nuclear version:**
0.6.37 Flatpak installed from Flathub

**Description of the issue:**
0.6.37 appears to have introduced a new bug. An error message pops up saying "A JavaScript error occurred in the main process" (see attached screenshot). When I click OK the window just re-opens. I have to kill the process to close the Nuclear window.

When I run Nuclear from the terminal (flatpak run org.js.nuclear.Nuclear) I get the following output (not sure if it's helpful, but including for completeness):  

```

main › (node:3) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
Gtk-Message: 17:26:49.221: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:26:49.221: Failed to load module "pk-gtk-module"
Gtk-Message: 17:26:49.222: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:26:49.222: Failed to load module "pk-gtk-module"
(node:85) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `exe --trace-deprecation ...` to show where the warning was created)
      main › Could not clear discord activity
      main › TypeError: Cannot read property 'write' of null
    at e.exports.send (/app/main/resources/app.asar/dist/webpack:/node_modules/discord-rpc/src/transports/ipc.js:155:17)
    at /app/main/resources/app.asar/dist/webpack:/node_modules/discord-rpc/src/client.js:166:22
    at new Promise (<anonymous>)
    at e.exports.request (/app/main/resources/app.asar/dist/webpack:/node_modules/discord-rpc/src/client.js:164:12)
    at e.exports.clearActivity (/app/main/resources/app.asar/dist/webpack:/node_modules/discord-rpc/src/client.js:550:17)
    at h.clear (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/discord/index.ts:105:24)
    at y.name [as onClearTrackList] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/player.ts:66:26)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
      main › Could not clear discord activity
      main › TypeError: Cannot read property 'write' of null
    at e.exports.send (/app/main/resources/app.asar/dist/webpack:/node_modules/discord-rpc/src/transports/ipc.js:155:17)
    at /app/main/resources/app.asar/dist/webpack:/node_modules/discord-rpc/src/client.js:166:22
    at new Promise (<anonymous>)
    at e.exports.request (/app/main/resources/app.asar/dist/webpack:/node_modules/discord-rpc/src/client.js:164:12)
    at e.exports.clearActivity (/app/main/resources/app.asar/dist/webpack:/node_modules/discord-rpc/src/client.js:550:17)
    at h.clear (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/discord/index.ts:105:24)
    at App.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/main.ts:116:19)
    at App.emit (events.js:327:22)
    at Object.showErrorBox (electron/js2c/browser_init.js:49:5603)
    at electron/js2c/browser_init.js:197:763
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)
   ipc api › error in event close => Object has been destroyed
   ipc api › TypeError: Object has been destroyed
    at _.close (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/services/window/index.ts:186:24)
    at f.name [as onClose] (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/settings.ts:31:17)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9715)
    at Object.emit (events.js:315:20)

``` 

Please let me know if you need more info. Happy to run additional tests to help debug.

**Comment by yang-musa** [comment]
![Screenshot from 2024-08-16 17-20-52](https://github.com/user-attachments/assets/aebf34c3-ac2b-4a1b-80d7-816596dd1e55)
 I forgot to include the screenshot of the error message, here it is...

**Comment by nukeop** [comment]
Hi, this is already solved: https://github.com/nukeop/nuclear/issues/1669

**Comment by yang-musa** [comment]
Can confirm MPRIS works now. Thanks!!

**Comment by nukeop** [comment]
Awesome, thank you for confirming.
