### ISSUE TITLE
Nuclear doesn't work on Ubuntu 12.10

### ISSUE THREAD

**Issue by gyammy80** [nukeop/nuclear#1718]
**Ubuntu 24.10**

**Nuclear version:0.6.39**

**I installed nuclear from snap
Here the error:
node:4641) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.org.chromium.Chromium.hCTUf9)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.@nuclear/scanner (/snap/nuclear/75/resources/app.asar/dist/main.js:4:9741864)
    at __webpack_require__ (/snap/nuclear/75/resources/app.asar/dist/main.js:1939:2675911)
    at Object../src/controllers/local-library.ts (/snap/nuclear/75/resources/app.asar/dist/main.js:4:9642653)
    at __webpack_require__ (/snap/nuclear/75/resources/app.asar/dist/main.js:1939:2675911)
    at Object../src/ioc.ts (/snap/nuclear/75/resources/app.asar/dist/main.js:4:9656960)
    at __webpack_require__ (/snap/nuclear/75/resources/app.asar/dist/main.js:1939:2675911)
    at Object../src/main.ts (/snap/nuclear/75/resources/app.asar/dist/main.js:4:9659050)
    at __webpack_require__ (/snap/nuclear/75/resources/app.asar/dist/main.js:1939:2675911)
    at /snap/nuclear/75/resources/app.asar/dist/main.js:1939:2677883
    at Object.<anonymous> (/snap/nuclear/75/resources/app.asar/dist/main.js:1939:2677943)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)

(nuclear:4641): Gtk-WARNING **: 12:58:18.179: Theme parsing error: gtk.css:1413:23: 'font-feature-settings' is not a valid property name

(nuclear:4641): Gtk-WARNING **: 12:58:18.185: Theme parsing error: gtk.css:3286:25: 'font-feature-settings' is not a valid property name

(nuclear:4641): Gtk-WARNING **: 12:58:18.185: Theme parsing error: gtk.css:3748:23: 'font-feature-settings' is not a valid property name
libGL error: MESA-LOADER: failed to open radeonsi (search paths /snap/nuclear/75/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast (search paths /snap/nuclear/75/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
libGL error: failed to load driver: swrast
**

**Comment by nukeop** [comment]
12.10 or 24.10?

**Comment by gyammy80** [comment]
24.10 sorry 

Il giorno 12 ott 2024, 13:15, alle ore 13:15, nukeop ***@***.***> ha scritto:

**Comment by carlospazuzu** [comment]
Funny enough, some applications stopped working on Ubuntu 24. The same happened to me with Obsidian.md, the workaround I found online is to run the command:

`echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns`

Don't quite remember where I found this and the motives it make it work, but it works. I hope it works for you as well.

**Comment by nukeop** [comment]
If it can be confirmed that it works, I'll add it to the troubleshooting docs.

**Comment by carlospazuzu** [comment]
In my case, I use the AppImage version, not sure if it may work with snap version.

Before running the command:
![image](https://github.com/user-attachments/assets/33887ed7-3f1f-4074-aa02-8a8f543d3f01)

After running the command:
![image](https://github.com/user-attachments/assets/b7201a6c-2e98-480e-91a4-75116329c4b0)

**Comment by gyammy80** [comment]
> Funny enough, some applications stopped working on Ubuntu 24. The same happened to me with Obsidian.md, the workaround I found online is to run the command:
> 
> `echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns`
> 
> Don't quite remember where I found this and the motives it make it work, but it works. I hope it works for you as well.

It doesn't work for me

**Comment by carlospazuzu** [comment]
> > Funny enough, some applications stopped working on Ubuntu 24. The same happened to me with Obsidian.md, the workaround I found online is to run the command:
> > `echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns`
> > Don't quite remember where I found this and the motives it make it work, but it works. I hope it works for you as well.
> 
> It doesn't work for me

Considered trying using the AppImage version?

**Comment by CoolSpot** [comment]
Snap package is broken for all OSes. Doesn't work on fresh 24.04.1 LTS, on 20.04 (#1656), and on 24.10 .

**Comment by nukeop** [comment]
Are you getting the same error as the OP? Does it launch? What CPU do you have?

**Comment by CoolSpot** [comment]
Yes, same error, app is not showing any UI:
```
$ nuclear 
    main › (node:103094) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.org.chromium.Chromium.wSHzeE)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.@nuclear/scanner (/snap/nuclear/76/resources/app.asar/dist/main.js:4:9794227)
    at __webpack_require__ (/snap/nuclear/76/resources/app.asar/dist/main.js:1939:2681932)
    at Object../src/controllers/local-library.ts (/snap/nuclear/76/resources/app.asar/dist/main.js:4:9694904)
    at __webpack_require__ (/snap/nuclear/76/resources/app.asar/dist/main.js:1939:2681932)
    at Object../src/ioc.ts (/snap/nuclear/76/resources/app.asar/dist/main.js:4:9709211)
    at __webpack_require__ (/snap/nuclear/76/resources/app.asar/dist/main.js:1939:2681932)
    at Object../src/main.ts (/snap/nuclear/76/resources/app.asar/dist/main.js:4:9711301)
    at __webpack_require__ (/snap/nuclear/76/resources/app.asar/dist/main.js:1939:2681932)
    at /snap/nuclear/76/resources/app.asar/dist/main.js:1939:2683904
    at Object.<anonymous> (/snap/nuclear/76/resources/app.asar/dist/main.js:1939:2683964)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)

(nuclear:103094): Gtk-WARNING **: 16:44:55.809: Theme parsing error: gtk.css:1422:23: 'font-feature-settings' is not a valid property name

(nuclear:103094): Gtk-WARNING **: 16:44:55.816: Theme parsing error: gtk.css:3308:25: 'font-feature-settings' is not a valid property name

(nuclear:103094): Gtk-WARNING **: 16:44:55.817: Theme parsing error: gtk.css:3770:23: 'font-feature-settings' is not a valid property name
^C
```

Fresh Ubuntu 24.04.1 LTS install , CPU is AMD Ryzen 5 3600:
```
$ uname -a
Linux ubuntu 6.8.0-49-generic #49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov  4 02:06:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

$ cat /proc/cpuinfo 
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 113
model name	: AMD Ryzen 5 3600 6-Core Processor
```

**Comment by nukeop** [comment]
I upgraded Electron in the newest release. If this reoccurs, please reopen.
