### ISSUE TITLE
 electron:dev not showing any window on mac

### ISSUE THREAD

**Issue by saimfd** [nukeop/nuclear#339]
Im trying to run nuclear in dev environment but it does not show any window on opening.

Node v11.7.0
NPM v6.5.0
OS: macOS Mojave 10.14.5

`npm run watch`:

```
> nuclear@0.4.5 watch /Users/saimfarid/Documents/HTML/FOSS/Projects/Nuclear/nuclear
> webpack-dev-server --inline --progress --env=dev

Happy[jsx]: Version: 5.0.1. Threads: 3
(node:11530) UnhandledPromiseRejectionWarning: Error: No open ports found in between 8080 and 8083
    at /Users/saimfarid/Documents/HTML/FOSS/Projects/Nuclear/nuclear/node_modules/portfinder/lib/portfinder.js:194:25
    at /Users/saimfarid/Documents/HTML/FOSS/Projects/Nuclear/nuclear/node_modules/portfinder/node_modules/async/lib/async.js:52:16
    at /Users/saimfarid/Documents/HTML/FOSS/Projects/Nuclear/nuclear/node_modules/portfinder/node_modules/async/lib/async.js:269:32
    at /Users/saimfarid/Documents/HTML/FOSS/Projects/Nuclear/nuclear/node_modules/portfinder/node_modules/async/lib/async.js:44:16
    at /Users/saimfarid/Documents/HTML/FOSS/Projects/Nuclear/nuclear/node_modules/portfinder/lib/portfinder.js:151:16
    at Server.onListen (/Users/saimfarid/Documents/HTML/FOSS/Projects/Nuclear/nuclear/node_modules/portfinder/lib/portfinder.js:43:7)
    at Object.onceWrapper (events.js:276:13)
    at Server.emit (events.js:188:13)
    at emitListeningNT (net.js:1288:10)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
(node:11530) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11530) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Happy[jsx]: All set; signaling webpack to proceed.
Happy[scss]: Version: 5.0.1. Threads: 3
Happy[scss]: All set; signaling webpack to proceed.
ℹ ｢wdm｣: Hash: 97b1141f1cc878b8cd02                                           . Version: webpack 4.32.2
Time: 7566ms
Built at: 06/02/2019 12:14:48 PM
        Asset      Size  Chunks             Chunk Names
    bundle.js  10.2 MiB    main  [emitted]  main
bundle.js.map    10 MiB    main  [emitted]  main
   index.html  2.18 KiB          [emitted]  
Entrypoint main = bundle.js bundle.js.map
[0] multi (webpack)-dev-server/client?http://localhost (webpack)/hot/dev-server.js react-hot-loader/patch webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./app/index.js 88 bytes {main} [built]
[./app/App.js] 18.5 KiB {main} [built]
[./app/index.js] 1.35 KiB {main} [built]
[./app/store/configureStore.js] 1.02 KiB {main} [built]
[./node_modules/babel-polyfill/lib/index.js] 833 bytes {main} [built]
[./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {main} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {main} [built]
[./node_modules/react-hot-loader/dist/react-hot-loader.development.js] 64 KiB {main} [built]
[./node_modules/react-hot-loader/index.js] 676 bytes {main} [built]
[./node_modules/react-hot-loader/patch.js] 228 bytes {main} [built]
[./node_modules/react-redux/es/index.js] 229 bytes {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost] (webpack)-dev-server/client?http://localhost 9.26 KiB {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 9.26 KiB {main} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.61 KiB {main} [built]
[./node_modules/webpack/hot/only-dev-server.js] (webpack)/hot/only-dev-server.js 2.55 KiB {main} [built]
    + 1938 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./index.html] 2.54 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
ℹ ｢wdm｣: Compiled successfully.
```

`npm run electron:dev`:

```
> nuclear@0.4.5 electron:dev /Users/saimfarid/Documents/HTML/FOSS/Projects/Nuclear/nuclear
> webpack --progress --colors --config=webpack.config.electron.js && electron ./bundle.electron.js

Happy[jsx]: Version: 5.0.1. Threads: 3
Happy[jsx]: All set; signaling webpack to proceed.
Hash: f302ffb41af1ab1b6b7e                                           t Version: webpack 4.32.2
Time: 3201ms
Built at: 06/02/2019 12:31:08 PM
             Asset      Size  Chunks             Chunk Names
bundle.electron.js  5.77 MiB    main  [emitted]  main
Entrypoint main = bundle.electron.js
[./app/constants/settings.js] 2.36 KiB {main} [built]
[./app/constants/settingsEnum.js] 163 bytes {main} [built]
[./app/globals.js] 386 bytes {main} [built]
[./app/rest/youtube-search.js] 598 bytes {main} [built]
[./server/downloads.js] 2.76 KiB {main} [built]
[./server/http/api/index.js] 2.23 KiB {main} [built]
[./server/http/lib/swagger.js] 3.85 KiB {main} [built]
[./server/http/middlewares.js] 1.07 KiB {main} [built]
[./server/http/server.js] 2.27 KiB {main} [built]
[./server/main.dev.js] 3.73 KiB {main} [built]
[./server/store.js] 1.46 KiB {main} [built]
[electron] external "electron" 42 bytes {main} [built]
[fs] external "fs" 42 bytes {main} [built]
[path] external "path" 42 bytes {main} [built]
[url] external "url" 42 bytes {main} [built]
    + 469 hidden modules
    main › Initialized settings store at /var/root/Library/Application Support/Electron/config.json
2019-06-02 12:31:08.977 Electron[12003:373672] *** WARNING: Textured window <AtomNSWindow: 0x7fb2cd301e70> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
http api › nuclear api available on port 4000
Added Extension:  React Developer Tools
Added Extension:  Redux DevTools
```

**Comment by patevs** [comment]
From `npm run watch` : `Error: No open ports found in between 8080 and 8083`
Looks like those ports are in use. 🍻
