### ISSUE TITLE
Local files don't get detected and shows an error in my terminal

### ISSUE THREAD

**Issue by farahnur42** [nukeop/nuclear#474]
Local files (primarily downloaded via Nuclear itself) aren't getting detected and every time I try to recheck local folders I get this error 
Error: [`<username>` being my username]
```
main › Error: Object has been destroyed
    at me (/home/<username>/Nuclear/release/linux-unpacked/resources/app.asar/dist/bundle.electron.js:348:38619)
    at he (/home/<username>/Nuclear/release/linux-unpacked/resources/app.asar/dist/bundle.electron.js:348:39344)
    at /home/<username>/Nuclear/release/linux-unpacked/resources/app.asar/dist/bundle.electron.js:348:38979
    at new Promise (<anonymous>)
    at fe (/home/<username>/Nuclear/release/linux-unpacked/resources/app.asar/dist/bundle.electron.js:348:38821)
    at /home/<username>/Nuclear/release/linux-unpacked/resources/app.asar/dist/bundle.electron.js:348:40218
    at l (/home/<username>/Nuclear/release/linux-unpacked/resources/app.asar/dist/bundle.electron.js:304:3265)
    at Generator._invoke (/home/<username>/Nuclear/release/linux-unpacked/resources/app.asar/dist/bundle.electron.js:304:3053)
    at Generator.forEach.e.(anonymous function) [as next] (/home/<username>/Nuclear/release/linux-unpacked/resources/app.asar/dist/bundle.electron.js:304:3688)
    at be (/home/<username>/Nuclear/release/linux-unpacked/resources/app.asar/dist/bundle.electron.js:348:39957)
```

Nuclear version: latest [I assume, even tho it says 0.5.0] (built from source, production version, node vers=12.10.0, npm vers=6.11.3) 
OS: OpenSUSE Tumbleweed x86_64
Reproducible steps: 
1. Run nuclear
2. Attach a local folder
3. Press the add music button

Expected behaviour: My music showing up 
![image](https://user-images.githubusercontent.com/37258115/65272322-ad190a00-db40-11e9-9edb-1d816f8ba24f.png)

**Comment by farahnur42** [comment]
After running electron:prod I'm getting this error instead but the problem still persists

```main › TypeError: Cannot read property '0' of undefined
    at /home/<username>/Nuclear/dist/bundle.electron.js:348:43494
    at l (/home/<username>/Nuclear/dist/bundle.electron.js:304:3265)
    at Generator._invoke (/home/<username>/Nuclear/dist/bundle.electron.js:304:3053)
    at Generator.forEach.e.(anonymous function) [as next] (/home/<username>/Nuclear/dist/bundle.electron.js:304:3688)
    at Ee (/home/<username>/Nuclear/dist/bundle.electron.js:348:42055)
    at o (/home/<username>/Nuclear/dist/bundle.electron.js:348:43918)
    at process._tickCallback (internal/process/next_tick.js:68:7)
````

**Comment by Mongogamer** [comment]
I had this same issue happen when untagged `.m4a` files were in my library. Once I added a proper title tag for them it worked fine again. Try checking if any files in your library miss the title or author tag.

**Comment by farahnur42** [comment]
Thanks a lot, tagging fixed it.
