### ISSUE TITLE
"npm run build:windows" fails on Windows

### ISSUE THREAD

**Issue by Venryx** [nukeop/nuclear#532]
Running `npm run build:windows` on Windows, to attempt to produce an exe file, fails with the following error: "env GITHASH is not defined"

Full stack-trace:
```
Error: Cannot cleanup:

Error #1 --------------------------------------------------------------------------------
Error: cannot expand pattern "${productName} Setup ${env.GITHASH}.${ext}": env GITHASH is not defined
    at pattern.replace (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\util\macroExpander.ts:51:19)
    at String.replace (<anonymous>)
    at expandMacro (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\util\macroExpander.ts:17:18)
    at WinPackager.expandMacro (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\platformPackager.ts:522:12)
    at WinPackager.computeArtifactName (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\platformPackager.ts:516:17)
    at WinPackager.expandArtifactNamePattern (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\platformPackager.ts:489:17)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:129:40
    at Generator.next (<anonymous>)
    at NsisTarget.buildInstaller (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:125:31)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:109:18
From previous event:
    at NsisTarget.buildInstaller (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:125:31)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:109:18
    at Generator.next (<anonymous>)
From previous event:
    at NsisTarget.finishBuild (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:107:20)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:438:36
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.doBuild (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:396:24)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\graceful-fs\graceful-fs.js:136:16
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\graceful-fs\graceful-fs.js:57:14
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:335:133)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\electron-builder\src\builder.ts:228:10)
    at then (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\electron-builder\src\cli\cli.ts:49:19)
    at <anonymous>

Error #2 --------------------------------------------------------------------------------
Error: cannot expand pattern "${productName}-${env.GITHASH}.${ext}": env GITHASH is not defined
    at pattern.replace (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\util\macroExpander.ts:51:19)
    at String.replace (<anonymous>)
    at expandMacro (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\util\macroExpander.ts:17:18)
    at WinPackager.expandMacro (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\platformPackager.ts:522:12)
    at WinPackager.computeArtifactName (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\platformPackager.ts:516:17)
    at WinPackager.expandArtifactNamePattern (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\platformPackager.ts:489:17)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:129:40
    at Generator.next (<anonymous>)
    at NsisTarget.buildInstaller (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:125:31)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:109:18
From previous event:
    at NsisTarget.buildInstaller (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:125:31)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:109:18
    at Generator.next (<anonymous>)
From previous event:
    at NsisTarget.finishBuild (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:107:20)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:438:36
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.doBuild (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:396:24)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\graceful-fs\graceful-fs.js:136:16
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\graceful-fs\graceful-fs.js:57:14
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:335:133)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\electron-builder\src\builder.ts:228:10)
    at then (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\electron-builder\src\cli\cli.ts:49:19)
    at <anonymous>
    at pattern.replace (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\util\macroExpander.ts:51:19)
    at String.replace (<anonymous>)
    at expandMacro (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\util\macroExpander.ts:17:18)
    at WinPackager.expandMacro (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\platformPackager.ts:522:12)
    at WinPackager.computeArtifactName (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\platformPackager.ts:516:17)
    at WinPackager.expandArtifactNamePattern (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\platformPackager.ts:489:17)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:129:40
    at Generator.next (<anonymous>)
    at NsisTarget.buildInstaller (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:125:31)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:109:18
    at NsisTarget.buildInstaller (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:125:31)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:109:18
    at Generator.next (<anonymous>)
    at NsisTarget.finishBuild (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:107:20)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:438:36
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
    at Packager.doBuild (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:396:24)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\graceful-fs\graceful-fs.js:136:16
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\graceful-fs\graceful-fs.js:57:14
    at FSReqWrap.oncomplete (fs.js:135:15)
    at Packager._build (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:335:133)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
    at Packager.build (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\electron-builder\src\builder.ts:228:10)
    at then (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\electron-builder\src\cli\cli.ts:49:19)
    at <anonymous>
    at pattern.replace (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\util\macroExpander.ts:51:19)
    at String.replace (<anonymous>)
    at expandMacro (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\util\macroExpander.ts:17:18)
    at WinPackager.expandMacro (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\platformPackager.ts:522:12)
    at WinPackager.computeArtifactName (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\platformPackager.ts:516:17)
    at WinPackager.expandArtifactNamePattern (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\platformPackager.ts:489:17)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:129:40
    at Generator.next (<anonymous>)
    at NsisTarget.buildInstaller (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:125:31)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:109:18
    at NsisTarget.buildInstaller (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:125:31)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:109:18
    at Generator.next (<anonymous>)
    at NsisTarget.finishBuild (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\targets\nsis\NsisTarget.ts:107:20)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:438:36
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
    at Packager.doBuild (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:396:24)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\graceful-fs\graceful-fs.js:136:16
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\graceful-fs\graceful-fs.js:57:14
    at FSReqWrap.oncomplete (fs.js:135:15)
    at Packager._build (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:335:133)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
    at Packager.build (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\electron-builder\src\builder.ts:228:10)
    at then (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\electron-builder\src\cli\cli.ts:49:19)
    at <anonymous>
    at throwError (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\builder-util\src\asyncTaskManager.ts:90:11)
    at checkErrors (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\builder-util\src\asyncTaskManager.ts:53:9)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\builder-util\src\asyncTaskManager.ts:67:7
From previous event:
    at AsyncTaskManager.awaitTasks (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\builder-util\src\asyncTaskManager.ts:44:19)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:442:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.doBuild (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:396:24)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\graceful-fs\graceful-fs.js:136:16
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\graceful-fs\graceful-fs.js:57:14
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:335:133)
    at C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\electron-builder\src\builder.ts:228:10)
    at then (C:\Root\Apps\@V\Nuclear\Main\packages\app\node_modules\electron-builder\src\cli\cli.ts:49:19)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nuclear@0.5.1 build:windows: `electron-builder -c.extraMetadata.main=dist/bundle.electron.js --windows --publish always`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nuclear@0.5.1 build:windows script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Stephen\AppData\Roaming\npm-cache\_logs\2019-10-16T04_08_34_870Z-debug.log
```

Where can I obtain the value to insert for the missing environment variable "GITHASH"?

**Comment by nukeop** [comment]
It should be the sha hash of the latest commit. It's only used for generating filenames for binaries.

**Comment by Venryx** [comment]
Adding "PLACEHOLDER" as the value for that environment variable did fix that error, and had it progress far enough to generate the main-exe and installer-exe files. I did get a later error about the "GHKEY" env-var being missing, but I assume that's only needed for the final step of uploading to the Github Releases section (which other developers won't have need of), so that's not an issue.

The part that is an issue is that the program appears to fail to load the web/UI part of the program when launched. All I get is a pure white screen. If I try to launch the exe from a terminal, no output is visible since apparently the process just immediately returns the terminal to typing mode, while continuing to run (cuts off its standard-output or something).

I doubt you know how to debug this at the moment (since works for you, and I have no error info); I'm just putting this info here for someone in the future when they attempt to debug this on their machine.

**Comment by nukeop** [comment]
I'll try to generate fresh windows binaries tomorrow for you. If you could try that, then we could pinpoint if the problem occurs only in your build process, or if something broke in the code.

**Comment by nukeop** [comment]
This should work now.
