### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by charliennnsdk** [nukeop/nuclear#64]
build or compile?
I used npm electron builder and it had errors

**Comment by nukeop** [comment]
The last section of README.md tells you how to build.
Production build is done via the following sequence:
```
$ npm run build:dist
$ npm run build:linux
```

Replace linux with macos or win to build for other systems.

**Comment by charliennnsdk** [comment]
When I build (windows), I have an error and get this message.

Error: Unresolved node modules: dbus
    at C:\Users\charlie\nuclear\node_modules\electron-builder-lib\src\util\packageDependencies.ts:109:19
From previous event:
    at Collector.resolveUnresolvedHoisted (C:\Users\charlie\nuclear\node_modules\electron-builder-lib\out\util\packageDependencies.js:206:11)
    at C:\Users\charlie\nuclear\node_modules\electron-builder-lib\src\util\packageDependencies.ts:85:18
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Collector.collect (C:\Users\charlie\nuclear\node_modules\electron-builder-lib\out\util\packageDependencies.js:154:11)
    at computeDependencies (C:\Users\charlie\nuclear\node_modules\electron-builder-lib\src\util\packageDependencies.ts:50:26)
    at C:\Users\charlie\nuclear\node_modules\electron-builder-lib\src\util\packageDependencies.ts:45:28
    at Generator.next (<anonymous>)
    at getProductionDependencies (C:\Users\charlie\nuclear\node_modules\electron-builder-lib\out\util\packageDependencies.js:29:21)
    at Lazy.<anonymous> (C:\Users\charlie\nuclear\node_modules\electron-builder-lib\src\packager.ts:98:24)
    at Generator.next (<anonymous>)
    at Lazy.get value [as value] (C:\Users\charlie\nuclear\node_modules\lazy-val\src\main.ts:18:23)
    at C:\Users\charlie\nuclear\node_modules\electron-builder-lib\src\util\yarn.ts:120:81
From previous event:
    at getProductionDependencies (C:\Users\charlie\nuclear\node_modules\electron-builder-lib\out\util\packageDependencies.js:29:21)
    at Lazy.<anonymous> (C:\Users\charlie\nuclear\node_modules\electron-builder-lib\src\packager.ts:98:24)
    at Generator.next (<anonymous>)
From previous event:
    at Lazy.get value [as value] (C:\Users\charlie\nuclear\node_modules\lazy-val\src\main.ts:18:23)
    at C:\Users\charlie\nuclear\node_modules\electron-builder-lib\src\util\yarn.ts:120:81
    at Generator.next (<anonymous>)
From previous event:
    at rebuild (C:\Users\charlie\nuclear\node_modules\electron-builder-lib\out\util\yarn.js:93:22)
    at C:\Users\charlie\nuclear\node_modules\electron-builder-lib\src\util\yarn.ts:20:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at installOrRebuild (C:\Users\charlie\nuclear\node_modules\electron-builder-lib\out\util\yarn.js:31:21)
    at C:\Users\charlie\nuclear\node_modules\electron-builder-lib\src\packager.ts:450:7
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (C:\Users\charlie\nuclear\node_modules\electron-builder-lib\out\packager.js:505:11)
    at C:\Users\charlie\nuclear\node_modules\electron-builder-lib\src\packager.ts:364:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (C:\Users\charlie\nuclear\node_modules\electron-builder-lib\out\packager.js:441:11)
    at C:\Users\charlie\nuclear\node_modules\electron-builder-lib\src\packager.ts:316:52
    at Generator.next (<anonymous>)
    at C:\Users\charlie\nuclear\node_modules\graceful-fs\graceful-fs.js:99:16
    at C:\Users\charlie\nuclear\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (C:\Users\charlie\nuclear\node_modules\electron-builder-lib\out\packager.js:385:11)
    at C:\Users\charlie\nuclear\node_modules\electron-builder-lib\src\packager.ts:278:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Packager.build (C:\Users\charlie\nuclear\node_modules\electron-builder-lib\out\packager.js:341:11)
    at C:\Users\charlie\nuclear\node_modules\electron-builder-lib\src\index.ts:50:40
    at Generator.next (<anonymous>)
From previous event:
    at build (C:\Users\charlie\nuclear\node_modules\electron-builder-lib\out\index.js:47:21)
    at build (C:\Users\charlie\nuclear\node_modules\electron-builder\src\builder.ts:228:10)
    at then (C:\Users\charlie\nuclear\node_modules\electron-builder\src\cli\cli.ts:48:33)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Object.args [as handler] (C:\Users\charlie\nuclear\node_modules\electron-builder\src\cli\cli.ts:48:33)
    at Object.runCommand (C:\Users\charlie\nuclear\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (C:\Users\charlie\nuclear\node_modules\yargs\yargs.js:1042:24)
    at Object.get [as argv] (C:\Users\charlie\nuclear\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (C:\Users\charlie\nuclear\node_modules\electron-builder\src\cli\cli.ts:42:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nuclear@0.4.3 build:windows: `electron-builder -c.extraMetadata.main=main.prod.js --windows`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nuclear@0.4.3 build:windows script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\charlie\AppData\Roaming\npm-cache\_logs\2018-03-25T16_51_59_683Z-debug.log

**Comment by nukeop** [comment]
Try removing optionalDependencies from package.json.

**Comment by charliennnsdk** [comment]
Thanks!
Build successed...but...
when I try to lauch the nuclear, I get this message
![image](https://user-images.githubusercontent.com/23337246/37881291-b8423b98-30d0-11e8-8ce6-d0c4921833cf.png)

**Comment by nukeop** [comment]
I'll look into that, might have to export server modules along with the rest of the project when building.

For now, try removing line 5 from main.prod.js and building again.
mpris is a linux module that lets users control nuclear from system widgets using dbus (system messages). So on windows, it's not used at all and can be deleted safely.

**Comment by charliennnsdk** [comment]
I deleted it, but I got this message again
![image](https://user-images.githubusercontent.com/23337246/37912584-ca44476e-314d-11e8-9d26-a4d4d6a32864.png)
So I deleted this, I got this message.
![default](https://user-images.githubusercontent.com/23337246/37912622-de844f30-314d-11e8-9cd4-c2c49d04dc94.JPG)

**Comment by nukeop** [comment]
I'll have to bundle the server files too when building. I'll work on this soon.

**Comment by nukeop** [comment]
Webpack had a very particular problem with mpris but now it's been solved once and for all. I'm gonna close this since it very definitely builds on windows.
