### ISSUE TITLE
0.6.1 snap does not work on mint 19.1

### ISSUE THREAD

**Issue by m-anish** [nukeop/nuclear#650]
The app launches, but I see errors in the console output. I can search for music, but when I try to play them, I see more errors. The logs are below.

```
      main › (node:26909) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
      main › (node:26909) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. (Connection ":1.325" is not allowed to own the service "org.mpris.MediaPlayer2.Nuclear_Music_Player" due to AppArmor policy)
    at Ze.emit (events.js:171:17)
    at r (/snap/nuclear/5/resources/app.asar/dist/main.js:2185:46879)
    at _bus.requestName.then.catch.e (/snap/nuclear/5/resources/app.asar/dist/main.js:2185:47136)
    at process._tickCallback (internal/process/next_tick.js:68:7)
      main › (node:26909) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
      main › (node:26909) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
  renderer › Error looking up streams for Billie Eilish bad guy on Jamendo
  renderer › {}
Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
  renderer › Error looking up streams for Dua Lipa doN'T StArT nOw on Jamendo
  renderer › {}
Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
  renderer › Error looking up streams for Radiohead Creep on Jamendo
  renderer › {}


```

OS: Mint 19.1
Nuclear version: 0.6.1 beta channel installed via snapcraft

**Comment by nukeop** [comment]
This is the same issue as #649

**Comment by nukeop** [comment]
Should be solved now, try the most recent release from the stable channel.

**Comment by m-anish** [comment]
tried with 0.6.3 from beta channel, and can report that this is fixed.
