### ISSUE TITLE
Theme parsing error

### ISSUE THREAD

**Issue by skrzek** [nukeop/nuclear#654]
Deepin 15.11 Since ver. 0.6.0. Nuclear won't start correctly.

`~$ nuclear`

`(nuclear:9760): Gtk-WARNING **: Theme parsing error: gtk.css:3611:22: 'none' is not a valid color name
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
      main › something fail during app bootstrap
      main › TypeError: Cannot read property 'indexOf' of undefined
    at Function.t.getFileName (/opt/nuclear/resources/app.asar/dist/main.js:1931:112553)
    at t (/opt/nuclear/resources/app.asar/dist/main.js:1931:111703)
    at Object../node_modules/abstract-socket/lib/abstract_socket.js (/opt/nuclear/resources/app.asar/dist/main.js:1925:99612)
    at n (/opt/nuclear/resources/app.asar/dist/main.js:1:211)
    at /opt/nuclear/resources/app.asar/dist/main.js:1985:16185
    at e.exports (/opt/nuclear/resources/app.asar/dist/main.js:1985:16778)
    at c (/opt/nuclear/resources/app.asar/dist/main.js:1985:5395)
    at Object.e.exports.sessionBus (/opt/nuclear/resources/app.asar/dist/main.js:1985:5597)
    at lt.p.init (/opt/nuclear/resources/app.asar/dist/main.js:2187:46373)
    at new p (/opt/nuclear/resources/app.asar/dist/main.js:2187:46190)`

**Comment by nukeop** [comment]
Thanks for the report. Some Deepin users said v0.6.3 works on their machines, have you tried that?

**Comment by skrzek** [comment]
@nukeop yes, this error is from v.0.6.3

**Comment by chaosmonk1** [comment]
I run into the same issue with 0.6.3 on Debian 10 and Trisquel 9 (based on Ubuntu 18.04), with both the .deb and the .AppImage.

**Comment by charjac** [comment]
Abstract-socket is a dependency of dbus-next wich is a dependency of mpris-service.
I build this appImage without mpris support.

https://cj-code.me/nextcloud/s/Z5kTbootrJTL5ds

@skrzek could you try it please ?
