### ISSUE TITLE
Tracks from local library don't play from favorite tracks and playlists

### ISSUE THREAD

**Issue by mYnDstrEAm** [nukeop/nuclear#728]
I can play tracks from the Local Library but I can't play them from the favorite tracks or a playlist after adding them.

Typically I get this error:   

> renderer › Error while searching  for TrackName on Youtube
> renderer › {}

and it doesn't start playing the track (it does load the album cover but it's stuck at 00:00).

Once an unrelated track from an online source started playing. Sometimes no error message shows.

Please solve this bug by ensuring that the local library location of the track is selected as first or only source of the track in all track lists if it was added from the local library.

It would also be good if the local library was selected as the default / first source of tracks for any track when searching for tracks.
And it would be best if there was a way to detect multiple versions of the same track at different sources and play from the source with the highest quality or the local library by default and only show one search result with the most appropriate title. These are probably separate, related issues.

v0.6.3 on Debian10/KDE

**Comment by nukeop** [comment]
> It would also be good if the local library was selected as the default / first source of tracks for any track when searching for tracks.

It already should be. If it's trying to search in other services first, that's probably a regression.

**Comment by mYnDstrEAm** [comment]
I tried it again: the song play under Local Library but when adding it to Favorite Tracks it doesn't start playing. When adding a song from an online source to Favorite Tracks it does start playing.
What could cause this? The only setting/plugin-setting I could find that could somehow be related to this was the setting for the default music source under Plugins. I changed this setting and then changed it back to the default setting. All the other settings should be the default ones as well.
If it wasn't a bug in the software but some other issue the song shouldn't play under Local Library either.

**Comment by nukeop** [comment]
I'll see if I can reproduce this

**Comment by mYnDstrEAm** [comment]
I tried it on another Debian10/KDE machine and I had exactly the same problem with the latest release (0.6.3).

I did not change any options or plugins before the problem first occurred.

However, I found that some tracks do play from favorites on both machines.

Under favorites the tracks that did play only had the following set in the config.json file:
artist, name, image, uuid.
The tracks that did not  play also had some additional information including streams (with the correct location of the file under "stream").

I added the track that played to favorites after adding some other tracks that didn't work and now the track that used to play under favorites doesn't play anymore either. It also has more information set just like the other tracks. Adding the track to favorites again removed the same track that I added earlier as the first track of the favorites.

I added the same track to a playlist from the local library and it did play from the playlist too even after the track stopped playing under favorites and after adding tracks which don't play from the playlist. I couldn't find a way to remove the track from the favorites. I could add the track a second time. Unlike for the favorites this did not remove the the same track that I added earlier as the first track of the playlist.

In the playlist the same track added from the local library works for one item of the playlist but not the other.

The item which works in the playlist has two streaming sources set (not the local filepath). The item which does not work has source:local.

**Comment by charjac** [comment]
Hi @mYnDstrEAm could you share one or more mp3 that don't work please ?

**Comment by mYnDstrEAm** [comment]
I don't think that this would be useful: most tracks didn't play. You could try it with a track that is "free download" on soundcloud (e.g. where you can click More->Download file; it usually says "Free Download" in the title). All of these didn't play. Maybe it's related to Local Library scanning somehow: #745

**Comment by mYnDstrEAm** [comment]
It still doesn't work with the latest version. I get this in the console and in red popups in the bottom right:
```
  renderer › Cannot read property 'name' of undefined
  renderer › s.map is not a function
```
Maybe it's because of some flawed filename in the music folder. I don't think it's because I run it sandboxed with firejail (and my Music folders are whitelisted in my local profile).

I already tried removing `~/.config/nuclear` and reinstalling the .deb package afterwards.

Do you have any suggestions what else to try? Does deleting the prior settings and cache require deleting something else? Any other logs to check? How can one specify the folder it check when clicking on Local Library? I could not find a setting for that and would try if it works with a folder with fewer tracks.

----

I can't use this app until this basic functionality works, please at least give some hints what else to try if you can't yet solve this.

This is the full output when starting up before these two messages:

```
      main › (node:26) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `nuclear --trace-deprecation ...` to show where the warning was created)
libGL error: MESA-LOADER: failed to retrieve device information

(nuclear:26): dbind-WARNING **: 09:02:25.475: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-x2MqE5VAyf: No such file or directory
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: failed to open /dev/dri/card0: No such file or directory
libGL error: failed to load driver: iris
      main › Could not connect to the sqlite database for local library
      main › a: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
    at p.loadDependencies (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/typeorm/driver/sqlite/SqliteDriver.js:130:19)
    at new p (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/typeorm/driver/sqlite/SqliteDriver.js:29:14)
    at t.DriverFactory.create (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/typeorm/driver/DriverFactory.js:44:24)
    at new t.DataSource (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/typeorm/data-source/DataSource.js:49:59)
    at T.connect (/opt/nuclear/resources/app.asar/dist/webpack:/@nuclear/main/src/services/local-library/db.ts:33:25)
    at App.<anonymous> (/opt/nuclear/resources/app.asar/dist/webpack:/@nuclear/main/src/main.ts:71:26)
    at App.emit (events.js:327:22)
      main › a: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
    at p.loadDependencies (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/typeorm/driver/sqlite/SqliteDriver.js:130:19)
    at new p (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/typeorm/driver/sqlite/SqliteDriver.js:29:14)
    at t.DriverFactory.create (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/typeorm/driver/DriverFactory.js:44:24)
    at new t.DataSource (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/typeorm/data-source/DataSource.js:49:59)
    at f.connect (/opt/nuclear/resources/app.asar/dist/webpack:/@nuclear/main/src/services/listening-history/db.ts:27:27)
    at App.<anonymous> (/opt/nuclear/resources/app.asar/dist/webpack:/@nuclear/main/src/main.ts:72:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
      main › Could not connect to the sqlite database for listening history
      main › a: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
    at p.loadDependencies (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/typeorm/driver/sqlite/SqliteDriver.js:130:19)
    at new p (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/typeorm/driver/sqlite/SqliteDriver.js:29:14)
    at t.DriverFactory.create (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/typeorm/driver/DriverFactory.js:44:24)
    at new t.DataSource (/opt/nuclear/resources/app.asar/dist/webpack:/node_modules/typeorm/data-source/DataSource.js:49:59)
    at f.connect (/opt/nuclear/resources/app.asar/dist/webpack:/@nuclear/main/src/services/listening-history/db.ts:27:27)
    at App.<anonymous> (/opt/nuclear/resources/app.asar/dist/webpack:/@nuclear/main/src/main.ts:72:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
   ipc api › error in event get-localfolders => Cannot read property 'find' of undefined
   ipc api › TypeError: Cannot read property 'find' of undefined
    at T.getLocalFolders (/opt/nuclear/resources/app.asar/dist/webpack:/@nuclear/main/src/services/local-library/db.ts:57:34)
    at h.name [as getLocalFolders] (/opt/nuclear/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/local-library.ts:42:47)
    at IpcMainImpl.<anonymous> (/opt/nuclear/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10374)
    at Object.emit (events.js:315:20)
   ipc api › error in event get-metas => Cannot read property 'find' of undefined
   ipc api › TypeError: Cannot read property 'find' of undefined
    at T.getTracks (/opt/nuclear/resources/app.asar/dist/webpack:/@nuclear/main/src/services/local-library/db.ts:80:33)
    at h.name [as getLocalMetas] (/opt/nuclear/resources/app.asar/dist/webpack:/@nuclear/main/src/controllers/local-library.ts:33:46)
    at IpcMainImpl.<anonymous> (/opt/nuclear/resources/app.asar/dist/webpack:/@nuclear/main/src/utils/container.ts:57:39)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10374)
    at Object.emit (events.js:315:20)
(node:98) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `exe --trace-deprecation ...` to show where the warning was created)

(nuclear:26): GLib-GIO-CRITICAL **: 09:02:35.236: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
```

**Comment by nukeop** [comment]
This should be working fine now, I tested it manually.
