### ISSUE TITLE
v0.6.5 - Error launching on Ubuntu 20.04.01 LTS

### ISSUE THREAD

**Issue by abacao** [nukeop/nuclear#767]
Tested on:  snap, deb and AppImage with the same result

```
$ ./nuclear-0.6.5.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: 
Something went wrong installing the "sharp" module

libvips-cpp.so.42: cannot open shared object file: No such file or directory

- Remove the "node_modules/sharp" directory then run
  "npm install --ignore-scripts=false --verbose" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (/tmp/.mount_nuclea3r51TR/resources/app.asar/node_modules/sharp/lib/constructor.js:34:9)
    at Object.<anonymous> (/tmp/.mount_nuclea3r51TR/resources/app.asar/node_modules/sharp/lib/constructor.js:338:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/.mount_nuclea3r51TR/resources/app.asar/node_modules/sharp/lib/index.js:3:15)
    at Object.<anonymous> (/tmp/.mount_nuclea3r51TR/resources/app.asar/node_modules/sharp/lib/index.js:15:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
```

**Comment by nathanfranke** [comment]
Same issue on Manjaro. Probably Linux issue as a whole

**Comment by lupa18** [comment]
Same here

**Comment by nukeop** [comment]
Yeah I'm working on it. There's a packaging issue. I can make it work on either windows or Linux, but not both. Apparently installing libvips locally can help, but this isn't a longterm solution (I need to figure out how to package sharp correctly).

**Comment by lupa18** [comment]
Ok, let me know if you need some help: I can test it on linux, windows, docker, etc..

**Comment by Nuke777** [comment]
Is the issue solved yet?
I am on MX KDE and still getting this.

**Comment by chaosmonk1** [comment]
> Apparently installing libvips locally can help

I installed `libvips42` on Debian testing, and the error changed to
```
libjpeg.so.8: cannot open shared object file: No such file or directory
```

I then installed every debian package with `libjpeg` in the name, but got the same error.

> There's a packaging issue. I can make it work on either windows or Linux, but not both.

Until you figure out packaging issue, can you perhaps put out a Linux-only release to try in the meantime? The last Nuclear release that worked on Debian-based distros was v0.5.1, more than a year ago, at first due to https://github.com/nukeop/nuclear/issues/654, and now this issue. I'm excited to see how the project has come along since v0.5.1 and was hoping this release would work.

**Comment by cypx** [comment]
Seem there is some improvements with the last CI build.

I try with https://github.com/nukeop/nuclear/suites/1152082002/artifacts/16615037 from https://github.com/nukeop/nuclear/runs/1078876430 on Ubuntu 20.04 and the only missing lib is libwebp.so.7
libwebp.so.7 do not seem to be officially build for Ubuntu 20.04 but it can be compile from project source

```bash
wget https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.1.0.tar.gz
tar xzf libwebp-1.1.0.tar.gz
cd libwebp-1.1.0/
./configure
make
sudo make install
sudo ln -s /usr/local/lib/libwebp.so.7 /usr/lib/x86_64-linux-gnu/libwebp.so.7
```
Or you could simply do a dirty fix linking previous libwebp version

```bash
sudo ln -s  /usr/lib/x86_64-linux-gnu/libwebp.so.6  /usr/lib/x86_64-linux-gnu/libwebp.so.7
```

Once it done nuclear 0.6.5 should work pretty fine.

**Comment by abacao** [comment]
@cypx 
The dirty fix didn't work on my side...

**Comment by nukeop** [comment]
I tried different ways of bundling `sharp` dependencies and can never get it to work in all cases. I'm looking into replacing it with something that doesn't require native modules.

**Comment by Ducote** [comment]
Works perfectly fine for me : Ubuntu 20.04.1 LTS (64bits)
Ubuntu 20.04
GPU : Nvidia GeForce GTX 970
GPU driver : nvidia driver 450 (libre)
Proc : AMD® Ryzen 9 3900x
