### ISSUE TITLE
Nuclear 0.4.3 does not launch

### ISSUE THREAD

**Issue by thecountoftuscany** [nukeop/nuclear#94]
Nuclear version: 0.4.3
Operating system: KDE Neon (Ubuntu 16.04 based distro)

As mentioned, Nuclear does not launch. On launching from terminal, the following is output:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot open /home/jcd/projects/electron/nuclear/node_modules/mpris-service/node_modules/dbus/build/Release/dbus.node: Error: /home/jcd/projects/electron/nuclear/node_modules/mpris-service/node_modules/dbus/build/Release/dbus.node: cannot open shared object file: No such file or directory
    at Object.<anonymous> (/opt/nuclear/resources/app.asar/dist/bundle.electron.js:24:84022)
    at Object../node_modules/mpris-service/node_modules/dbus/build/Release/dbus.node (/opt/nuclear/resources/app.asar/dist/bundle.electron.js:24:84159)
    at n (/opt/nuclear/resources/app.asar/dist/bundle.electron.js:1:265)
    at Object../node_modules/mpris-service/node_modules/dbus/lib/dbus.js (/opt/nuclear/resources/app.asar/dist/bundle.electron.js:24:86593)
    at n (/opt/nuclear/resources/app.asar/dist/bundle.electron.js:1:265)
    at Object../node_modules/mpris-service/index.js (/opt/nuclear/resources/app.asar/dist/bundle.electron.js:24:75045)
    at n (/opt/nuclear/resources/app.asar/dist/bundle.electron.js:1:265)
    at Object../server/main.prod.linux.js (/opt/nuclear/resources/app.asar/dist/bundle.electron.js:24:143406)
    at n (/opt/nuclear/resources/app.asar/dist/bundle.electron.js:1:265)
    at e../app/constants/settings.js.e.exports.name (/opt/nuclear/resources/app.asar/dist/bundle.electron.js:1:1057)
```
and the process does not exit till a keyboard interrupt is made or it is killed.

**Comment by mikelpint** [comment]
Same on Arch Linux

**Comment by nukeop** [comment]
I guess I'll have to disable mpris support for now, then use a pure js-based module for that in the future (not a native one). There's no easy way to bundle it for every distro.

**Comment by nukeop** [comment]
Okay, I update the binaries. Download them again and try running now. Mpris will be disabled, but the rest should work. Sorry for the fuckup.

Since node-loader uses an absolute path, the binaries worked on the machine I built them, but would not run on your computers. That's why I thought they were good to go.

**Comment by thecountoftuscany** [comment]
The updated binary works now. Though, I depend on mpris for controlling all media playback on my computer. Still thanks a lot for your efforts!

**Comment by nukeop** [comment]
Yeah I use mpris a lot myself. I will put a priority on restoring this functionality in 0.4.4, shouldn't be too hard.
